Repository johnbillion/query-monitor, pull requests merged in 2021-12, with the labels that each got.

#598 Add CPU Architecture to the Server environment
  collectors/environment.php
  output/html/environment.php
Labels: type:enhancement, collector:environment

#618 Fix WP-CLI error message
  classes/CLI.php
Labels: type:bug

#615 (fix): correct time output in rest api
  output/raw/db_queries.php
Labels: type:bug, dispatcher:rest

#590 Cease and detach
  assets/query-monitor.js
  classes/Collector.php
  classes/Collectors.php
  classes/Dispatcher.php
  classes/Dispatchers.php
  classes/QueryMonitor.php
  collectors/assets.php
  collectors/block_editor.php
  collectors/caps.php
  collectors/http.php
  collectors/languages.php
  collectors/logger.php
  collectors/overview.php
  collectors/php_errors.php
  collectors/redirects.php
  collectors/theme.php
  collectors/timing.php
  dispatchers/Html.php
  tests/phpunit/test-dispatcher-html.php
  wp-content/db.php
Labels: type:enhancement

#632 Introduce plugin version constant
  query-monitor.php
Labels: type:enhancement, component:bootstrap
